default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: homeday_user
  password: homeday5612
  host: db

development:
  <<: *default
  database: property_service

test:
  <<: *default
  database: property_service_test

production:
  <<: *default
  database: property_service
  username: homeday_user
  password: homeday5612